services:
  anybus-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anybus_app
    ports:
      - "7184:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    restart: unless-stopped
    networks:
      - caonima-wang

networks:
  caonima-wang:
    external: true
